#pragma once

#include <stdint.h>

typedef enum KeyCode_t
{
	KeyCode_Space = 32,
	KeyCode_Apostrophe = 39,
	KeyCode_Comma = 44,
	KeyCode_Minus = 45,
	KeyCode_Period = 46,
	KeyCode_Slash = 47,

	KeyCode_D0 = 48,
	KeyCode_D1 = 49,
	KeyCode_D2 = 50,
	KeyCode_D3 = 51,
	KeyCode_D4 = 52,
	KeyCode_D5 = 53,
	KeyCode_D6 = 54,
	KeyCode_D7 = 55,
	KeyCode_D8 = 56,
	KeyCode_D9 = 57,

	KeyCode_Semicolon = 59,
	KeyCode_Equal = 61,

	KeyCode_A = 65,
	KeyCode_B = 66,
	KeyCode_C = 67,
	KeyCode_D = 68,
	KeyCode_E = 69,
	KeyCode_F = 70,
	KeyCode_G = 71,
	KeyCode_H = 72,
	KeyCode_I = 73,
	KeyCode_J = 74,
	KeyCode_K = 75,
	KeyCode_L = 76,
	KeyCode_M = 77,
	KeyCode_N = 78,
	KeyCode_O = 79,
	KeyCode_P = 80,
	KeyCode_Q = 81,
	KeyCode_R = 82,
	KeyCode_S = 83,
	KeyCode_T = 84,
	KeyCode_U = 85,
	KeyCode_V = 86,
	KeyCode_W = 87,
	KeyCode_X = 88,
	KeyCode_Y = 89,
	KeyCode_Z = 90,

	KeyCode_LeftBracket = 91,
	KeyCode_Backslash = 92,
	KeyCode_RightBracket = 93,
	KeyCode_GraveAccent = 96,

	KeyCode_World1 = 161,
	KeyCode_World2 = 162,

	KeyCode_Escape = 256,
	KeyCode_Enter = 257,
	KeyCode_Tab = 258,
	KeyCode_Backspace = 259,
	KeyCode_Insert = 260,
	KeyCode_Delete = 261,
	KeyCode_Right = 262,
	KeyCode_Left = 263,
	KeyCode_Down = 264,
	KeyCode_Up = 265,
	KeyCode_PageUp = 266,
	KeyCode_PageDown = 267,
	KeyCode_Home = 268,
	KeyCode_End = 269,
	KeyCode_CapsLock = 280,
	KeyCode_ScrollLock = 281,
	KeyCode_NumLock = 282,
	KeyCode_PrintScreen = 283,
	KeyCode_Pause = 284,

	KeyCode_F1 = 290,
	KeyCode_F2 = 291,
	KeyCode_F3 = 292,
	KeyCode_F4 = 293,
	KeyCode_F5 = 294,
	KeyCode_F6 = 295,
	KeyCode_F7 = 296,
	KeyCode_F8 = 297,
	KeyCode_F9 = 298,
	KeyCode_F10 = 299,
	KeyCode_F11 = 300,
	KeyCode_F12 = 301,
	KeyCode_F13 = 302,
	KeyCode_F14 = 303,
	KeyCode_F15 = 304,
	KeyCode_F16 = 305,
	KeyCode_F17 = 306,
	KeyCode_F18 = 307,
	KeyCode_F19 = 308,
	KeyCode_F20 = 309,
	KeyCode_F21 = 310,
	KeyCode_F22 = 311,
	KeyCode_F23 = 312,
	KeyCode_F24 = 313,
	KeyCode_F25 = 314,

	KeyCode_KP0 = 320,
	KeyCode_KP1 = 321,
	KeyCode_KP2 = 322,
	KeyCode_KP3 = 323,
	KeyCode_KP4 = 324,
	KeyCode_KP5 = 325,
	KeyCode_KP6 = 326,
	KeyCode_KP7 = 327,
	KeyCode_KP8 = 328,
	KeyCode_KP9 = 329,
	KeyCode_KPDecimal = 330,
	KeyCode_KPDivide = 331,
	KeyCode_KPMultiply = 332,
	KeyCode_KPSubtract = 333,
	KeyCode_KPAdd = 334,
	KeyCode_KPEnter = 335,
	KeyCode_KPEqual = 336,

	KeyCode_LeftShift = 340,
	KeyCode_LeftControl = 341,
	KeyCode_LeftAlt = 342,
	KeyCode_LeftSuper = 343,
	KeyCode_RightShift = 344,
	KeyCode_RightControl = 345,
	KeyCode_RightAlt = 346,
	KeyCode_RightSuper = 347,
	KeyCode_Menu = 348,
} KeyCode;

#define KEY_SPACE           KeyCode_Space
#define KEY_APOSTROPHE      KeyCode_Apostrophe    
#define KEY_COMMA           KeyCode_Comma         
#define KEY_MINUS           KeyCode_Minus         
#define KEY_PERIOD          KeyCode_Period        
#define KEY_SLASH           KeyCode_Slash     

#define KEY_0               KeyCode_D0
#define KEY_1               KeyCode_D1
#define KEY_2               KeyCode_D2
#define KEY_3               KeyCode_D3
#define KEY_4               KeyCode_D4
#define KEY_5               KeyCode_D5
#define KEY_6               KeyCode_D6
#define KEY_7               KeyCode_D7
#define KEY_8               KeyCode_D8
#define KEY_9               KeyCode_D9

#define KEY_SEMICOLON       KeyCode_Semicolon    
#define KEY_EQUAL           KeyCode_Equal      

#define KEY_A               KeyCode_A
#define KEY_B               KeyCode_B
#define KEY_C               KeyCode_C
#define KEY_D               KeyCode_D
#define KEY_E               KeyCode_E
#define KEY_F               KeyCode_F
#define KEY_G               KeyCode_G
#define KEY_H               KeyCode_H
#define KEY_I               KeyCode_I
#define KEY_J               KeyCode_J
#define KEY_K               KeyCode_K
#define KEY_L               KeyCode_L
#define KEY_M               KeyCode_M
#define KEY_N               KeyCode_N
#define KEY_O               KeyCode_O
#define KEY_P               KeyCode_P
#define KEY_Q               KeyCode_Q
#define KEY_R               KeyCode_R
#define KEY_S               KeyCode_S
#define KEY_T               KeyCode_T
#define KEY_U               KeyCode_U
#define KEY_V               KeyCode_V
#define KEY_W               KeyCode_W
#define KEY_X               KeyCode_X
#define KEY_Y               KeyCode_Y
#define KEY_Z               KeyCode_Z

#define KEY_LEFT_BRACKET    KeyCode_LeftBracket  
#define KEY_BACKSLASH       KeyCode_Backslash    
#define KEY_RIGHT_BRACKET   KeyCode_RightBracket 
#define KEY_GRAVE_ACCENT    KeyCode_GraveAccent  
#define KEY_WORLD_1         KeyCode_World1       
#define KEY_WORLD_2         KeyCode_World2       

#define KEY_ESCAPE          KeyCode_Escape
#define KEY_ENTER           KeyCode_Enter
#define KEY_TAB             KeyCode_Tab
#define KEY_BACKSPACE       KeyCode_Backspace
#define KEY_INSERT          KeyCode_Insert
#define KEY_DELETE          KeyCode_Delete
#define KEY_RIGHT           KeyCode_Right
#define KEY_LEFT            KeyCode_Left
#define KEY_DOWN            KeyCode_Down
#define KEY_UP              KeyCode_Up

#define KEY_PAGE_UP         KeyCode_PageUp
#define KEY_PAGE_DOWN       KeyCode_PageDown
#define KEY_HOME            KeyCode_Home
#define KEY_END             KeyCode_End
#define KEY_CAPS_LOCK       KeyCode_CapsLock
#define KEY_SCROLL_LOCK     KeyCode_ScrollLock
#define KEY_NUM_LOCK        KeyCode_NumLock
#define KEY_PRINT_SCREEN    KeyCode_PrintScreen
#define KEY_PAUSE           KeyCode_Pause

#define KEY_F1              KeyCode_F1
#define KEY_F2              KeyCode_F2
#define KEY_F3              KeyCode_F3
#define KEY_F4              KeyCode_F4
#define KEY_F5              KeyCode_F5
#define KEY_F6              KeyCode_F6
#define KEY_F7              KeyCode_F7
#define KEY_F8              KeyCode_F8
#define KEY_F9              KeyCode_F9
#define KEY_F10             KeyCode_F10
#define KEY_F11             KeyCode_F11
#define KEY_F12             KeyCode_F12
#define KEY_F13             KeyCode_F13
#define KEY_F14             KeyCode_F14
#define KEY_F15             KeyCode_F15
#define KEY_F16             KeyCode_F16
#define KEY_F17             KeyCode_F17
#define KEY_F18             KeyCode_F18
#define KEY_F19             KeyCode_F19
#define KEY_F20             KeyCode_F20
#define KEY_F21             KeyCode_F21
#define KEY_F22             KeyCode_F22
#define KEY_F23             KeyCode_F23
#define KEY_F24             KeyCode_F24
#define KEY_F25             KeyCode_F25

#define KEY_KP_0            KeyCode_KP0
#define KEY_KP_1            KeyCode_KP1
#define KEY_KP_2            KeyCode_KP2
#define KEY_KP_3            KeyCode_KP3
#define KEY_KP_4            KeyCode_KP4
#define KEY_KP_5            KeyCode_KP5
#define KEY_KP_6            KeyCode_KP6
#define KEY_KP_7            KeyCode_KP7
#define KEY_KP_8            KeyCode_KP8
#define KEY_KP_9            KeyCode_KP9
#define KEY_KP_DECIMAL      KeyCode_KPDecimal
#define KEY_KP_DIVIDE       KeyCode_KPDivide
#define KEY_KP_MULTIPLY     KeyCode_KPMultiply
#define KEY_KP_SUBTRACT     KeyCode_KPSubtract
#define KEY_KP_ADD          KeyCode_KPAdd
#define KEY_KP_ENTER        KeyCode_KPEnter
#define KEY_KP_EQUAL        KeyCode_KPEqual

#define KEY_LEFT_SHIFT       KeyCode_LeftShift
#define KEY_LEFT_CONTROL     KeyCode_LeftControl
#define KEY_LEFT_ALT         KeyCode_LeftAlt
#define KEY_LEFT_SUPER       KeyCode_LeftSuper
#define KEY_RIGHT_SHIFT      KeyCode_RightShift
#define KEY_RIGHT_CONTROL    KeyCode_RightControl
#define KEY_RIGHT_ALT        KeyCode_RightAlt
#define KEY_RIGHT_SUPER      KeyCode_RightSuper
#define KEY_MENU             KeyCode_Menu
